In [ ]:
!python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([99, 99])))"

2021-05-31 16:24:53.839804: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-05-31 16:24:55.567830: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-05-31 16:24:55.649668: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-05-31 16:24:55.649758: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (fa7214bc752a): /proc/driver/nvidia/version does not exist
tf.Tensor(-40.86964, shape=(), dtype=float32)


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
if tf.test.gpu_device_name() == '/device:GPU:0':
  print("Using a GPU")
else:
  print("Using a CPU")

Using a GPU


In [ ]:
import tensorflow as tf
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 4024254152465233954
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 10780885942879961341
physical_device_desc: "device: XLA_GPU device"
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 12567651201342837307
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 15651091252
locality {
  bus_id: 1
  links {
  }
}
incarnation: 10922718326167081695
physical_device_desc: "device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:03:00.0, compute capability: 7.0"
]


In [ ]:
with tf.device('/device:GPU:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
  c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))

2021-05-31 14:28:57.251221: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-31 14:28:57.251287: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-31 14:28:57.251311: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DMED7596): /proc/driver/nvidia/version does not exist
2021-05-31 14:28:57.251747: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


AttributeError: module 'tensorflow' has no attribute 'Session'

In [ ]:
# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))

AttributeError: module 'tensorflow' has no attribute 'Session'

In [ ]:
#!pwd

In [ ]:
import pandas as pd
data = pd.read_csv("HeLa/ayu/new/P value 0.05.csv")
data.head(2)
data.shape

FileNotFoundError: [Errno 2] No such file or directory: 'HeLa/ayu/new/P value 0.05.csv'

In [ ]:
df=pd.DataFrame(data)
X = df.iloc[:, :32]
y = df.iloc[:, 33]

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)
list(le.classes_)
values=le.transform(y)
print(values)

[2 2 2 2 2 2 2 2 1 1 1 1 0 0 0 0 0 0 0]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(le.transform(y).reshape(-1,1))
enc.categories_
#print(enc.transform(le.transform(y).reshape(-1,1)))

[array([0, 1, 2])]

In [ ]:
#print(np.array(tf.one_hot(le.transform(y), depth=3)))
#vocabulary_feature_column =  tf.feature_column.categorical_column_with_vocabulary_list(key=["P", "V", "K"],vocabulary_list=["P", "V", "K"])
import numpy as np
n_values = np.max(values) + 1
Y=np.eye(n_values)[values]

In [ ]:
#Y=pd.DataFrame(np.array(tf.one_hot(le.transform(y), depth=3)))
Y=pd.DataFrame(Y)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, random_state = 0)
X_train.to_csv("X_train.csv", index = False, header = None)
X_test.to_csv("X_test.csv", index = False, header = None)
Y_train.to_csv("Y_train.csv", index = False, header = None)
Y_test.to_csv("Y_test.csv", index = False, header = None)
Y_test.head()

0    1    2
10  0.0  1.0  0.0
1   0.0  0.0  1.0

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train.shape[1],Y_train.shape[1] 

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


(32, 3)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [ ]:
classifier = Sequential()
classifier.add(Dense(units = 9, activation = 'relu', input_dim=X_train.shape[1]))
classifier.add(Dense(units = 6, activation = 'relu'))
classifier.add(Dense(units = Y_train.shape[1] , activation = 'sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [ ]:
classifier.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

In [ ]:
classifier.fit(X_train, Y_train, batch_size = X_train.shape[1],epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
17/17 [==============================] - 1s 68ms/step - loss: 0.3649 - acc: 0.1176
Epoch 2/100
17/17 [==============================] - 0s 195us/step - loss: 0.3613 - acc: 0.1176
Epoch 3/100
17/17 [==============================] - 0s 179us/step - loss: 0.3578 - acc: 0.1765
Epoch 4/100
17/17 [==============================] - 0s 167us/step - loss: 0.3544 - acc: 0.1765
Epoch 5/100
17/17 [==============================] - 0s 160us/step - loss: 0.3510 - acc: 0.1765
Epoch 6/100
17/17 [==============================] - 0s 156us/step - loss: 0.3479 - acc: 0.2353
Epoch 7/100
17/17 [==============================] - 0s 158us/step - loss: 0.3450 - acc: 0.2353
Epoch 8/100
17/17 [==============================] - 0s 163us/step - loss: 0.3422 - acc: 0.2353
Epoch 9/100
17/17 [==============================] - 0s 160us/step - loss: 0.3393 - acc: 0.2353
Epoch 10/100
17/17 [==============================] - 0s 167us/step - loss: 0.3365 - acc:

In [ ]:
Y_pred = classifier.predict(X_test)
#Y_pred
y_pred=(Y_pred.argmax(1)[:,None] == np.arange(Y_pred.shape[1])).astype(int)
y_pred

array([[0, 1, 0],
       [0, 0, 1]])

In [ ]:
y_test=Y_test.values
y_test=(y_test.argmax(1)[:,None] == np.arange(y_test.shape[1])).astype(int)
y_test

array([[0, 1, 0],
       [0, 0, 1]])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))
cm

array([[1, 0],
       [0, 1]])

In [ ]:
# Install TensorFlow Dececision Forests.
!pip install tensorflow_decision_forests
# Use wurlitzer to capture training logs.
!pip install wurlitzer

     |████████████████████████████████| 6.2MB 5.5MB/s 


In [ ]:
import tensorflow_decision_forests as tfdf

import os
import numpy as np
import pandas as pd
import tensorflow as tf
import math
import collections
try:
  from wurlitzer import sys_pipes
except:
  from colabtools.googlelog import CaptureLog as sys_pipes
from IPython.core.magic import register_line_magic
from IPython.display import Javascript
@register_line_magic
def set_cell_height(size):
  display(
      Javascript("google.colab.output.setIframeHeight(0, true, {maxHeight: " +
                 str(size) + "})"))

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [36]:
#from file icon, right click => https://www.roelpeters.be/running-an-r-kernel-in-google-colab/ 
dataset_df = pd.read_excel("/content/drive/My Drive/Prediction analysis.xlsx")
print(dataset_df.head(3))

  Unnamed: 0  Mayo Score  ...  Escherichia-Shigella  Streptococcus-total
0    BKT-26N           2  ...              0.011318             0.017950
1    BKT-28N           1  ...              0.001136             0.030205
2    BKT-29N           2  ...              0.000000             0.014890

[3 rows x 26 columns]


In [39]:
dataset_df = pd.read_csv("/content/drive/My Drive/Prediction analysis.merged_class.csv")
print(dataset_df.head(3))

   Prevotella-Total  Other-Total  ...  Streptococcus-total      Class
0          0.122650     0.111059  ...             0.017950  Remission
1          0.001408     0.013444  ...             0.030205  Remission
2          0.000023     0.033736  ...             0.014890  Remission

[3 rows x 20 columns]


In [40]:
#dataset_tf = tfdf.keras.pd_dataframe_to_tf_dataset(dataset_df, label="Mayo Score")
dataset_tf = tfdf.keras.pd_dataframe_to_tf_dataset(dataset_df, label="Class")
model = tfdf.keras.RandomForestModel(compute_oob_variable_importances=True)
model.fit(x=dataset_tf)

3/3 [==============================] - 0s 7ms/step


In [41]:
%set_cell_height 300
model.summary()

<IPython.core.display.Javascript object>

Model: "random_forest_model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Total params: 1
Trainable params: 0
Non-trainable params: 1
_________________________________________________________________
Type: "RANDOM_FOREST"
Task: CLASSIFICATION
Label: "__LABEL"

Input Features (19):
	Alloprevotella
	Bacteroides
	Bifidobacterium
	Blautia
	Collinsella
	Coprococcus-Total
	Dialister
	Dorea
	Escherichia-Shigella
	Faecalibacterium
	Lachnospiraceae-Total
	Lactobacillus
	Other-Total
	Prevotella-Total
	Roseburia
	Ruminococcaceae-Total
	Ruminococcus-Total
	Streptococcus-total
	uncultured/unidentified-total

No weights

Variable Importance: MEAN_DECREASE_IN_ACCURACY:
    1. "uncultured/unidentified-total"  0.015873 ################
    2.                       "Blautia"  0.005291 ###########
    3.                   "Collinsella"  0.005291 ###########
    4.                     "Roseburia"  0.005291 ###########

In [42]:
tfdf.model_plotter.plot_model_in_colab(model, tree_idx=0, max_depth=3)

In [43]:
inspector = model.make_inspector()
?inspector.model_type

In [44]:
[field for field in dir(inspector) if not field.startswith("_")]

['MODEL_NAME',
 'dataspec',
 'evaluation',
 'export_to_tensorboard',
 'extract_tree',
 'features',
 'iterate_on_nodes',
 'label',
 'label_classes',
 'model_type',
 'num_trees',
 'objective',
 'specialized_header',
 'task',
 'training_logs',
 'variable_importances',
 'winner_take_all_inference']

In [45]:
from ipywidgets import interact, interactive, fixed, interact_manual
def select_subject(subID):
    df_filtered= dataset_df[subID]
    ax = df_filtered.apply(np.sum).hist(color="orange")
subject = dataset_df.columns
interact(select_subject, subID=subject)

interactive(children=(Dropdown(description='subID', options=('Prevotella-Total', 'Other-Total', 'Ruminococcace…

<function __main__.select_subject>

In [46]:
print("Model type:", inspector.model_type())
print("Number of trees:", inspector.num_trees())
print("Objective:", inspector.objective())
print("Input features:", inspector.features())

Model type: RANDOM_FOREST
Number of trees: 300
Objective: Classification(label=__LABEL, class=None, num_classes=7)
Input features: ["Alloprevotella" (1; #0), "Bacteroides" (1; #1), "Bifidobacterium" (1; #2), "Blautia" (1; #3), "Collinsella" (1; #4), "Coprococcus-Total" (1; #5), "Dialister" (1; #6), "Dorea" (1; #7), "Escherichia-Shigella" (1; #8), "Faecalibacterium" (1; #9), "Lachnospiraceae-Total" (1; #10), "Lactobacillus" (1; #11), "Other-Total" (1; #12), "Prevotella-Total" (1; #13), "Roseburia" (1; #14), "Ruminococcaceae-Total" (1; #15), "Ruminococcus-Total" (1; #16), "Streptococcus-total" (1; #17), "uncultured/unidentified-total" (1; #18)]


In [47]:
inspector.evaluation()

Evaluation(num_examples=189, accuracy=0.20105820105820105, loss=2.358559215589175, rmse=None, ndcg=None, aucs=None)

In [48]:
for importance in inspector.variable_importances().keys():
  print("\t", importance)

	 MEAN_DECREASE_IN_AP_1_VS_OTHERS
	 MEAN_DECREASE_IN_PRAUC_4_VS_OTHERS
	 MEAN_DECREASE_IN_AUC_1_VS_OTHERS
	 MEAN_DECREASE_IN_AP_5_VS_OTHERS
	 MEAN_DECREASE_IN_PRAUC_3_VS_OTHERS
	 MEAN_DECREASE_IN_AUC_5_VS_OTHERS
	 MEAN_DECREASE_IN_AP_4_VS_OTHERS
	 MEAN_DECREASE_IN_PRAUC_2_VS_OTHERS
	 MEAN_DECREASE_IN_AUC_4_VS_OTHERS
	 MEAN_DECREASE_IN_AP_3_VS_OTHERS
	 MEAN_DECREASE_IN_PRAUC_1_VS_OTHERS
	 MEAN_DECREASE_IN_AUC_3_VS_OTHERS
	 MEAN_DECREASE_IN_AP_2_VS_OTHERS
	 MEAN_DECREASE_IN_PRAUC_5_VS_OTHERS
	 MEAN_DECREASE_IN_AUC_2_VS_OTHERS
	 MEAN_DECREASE_IN_ACCURACY
	 NUM_AS_ROOT


In [49]:
# Mean decrease in AUC of the class 1 vs the others.
inspector.variable_importances()["MEAN_DECREASE_IN_AUC_1_VS_OTHERS"]

[("uncultured/unidentified-total" (1; #18), 0.0712471424942854),
 ("Coprococcus-Total" (1; #5), 0.004064008128016439),
 ("Roseburia" (1; #14), -0.0026035052070103037),
 ("Bacteroides" (1; #1), -0.00711201422402824),
 ("Bifidobacterium" (1; #2), -0.008572517145033987),
 ("Other-Total" (1; #12), -0.00927101854203688),
 ("Blautia" (1; #3), -0.0106680213360425),
 ("Collinsella" (1; #4), -0.011049022098043981),
 ("Dialister" (1; #6), -0.01130302260604521),
 ("Faecalibacterium" (1; #9), -0.012763525527051123),
 ("Dorea" (1; #7), -0.01295402590805178),
 ("Alloprevotella" (1; #0), -0.013398526797053334),
 ("Ruminococcaceae-Total" (1; #15), -0.013779527559054872),
 ("Streptococcus-total" (1; #17), -0.01771653543307078),
 ("Lactobacillus" (1; #11), -0.019177038354076748),
 ("Prevotella-Total" (1; #13), -0.021018542037083976),
 ("Lachnospiraceae-Total" (1; #10), -0.021209042418084634),
 ("Ruminococcus-Total" (1; #16), -0.021844043688087067),
 ("Escherichia-Shigella" (1; #8), -0.031750063500126824

In [50]:
inspector.extract_tree(tree_idx=0)

Tree(NonLeafNode(condition=(uncultured/unidentified-total >= 0.004005628637969494; miss=True), pos_child=NonLeafNode(condition=(Alloprevotella >= 0.003357323817908764; miss=True), pos_child=NonLeafNode(condition=(Roseburia >= 0.016060752794146538; miss=True), pos_child=NonLeafNode(condition=(Other-Total >= 0.06574533879756927; miss=True), pos_child=NonLeafNode(condition=(Lachnospiraceae-Total >= 0.01758013665676117; miss=False), pos_child=LeafNode(value=ProbabilityValue([0.0, 0.0, 0.2, 0.0, 0.8],n=5.0)), neg_child=LeafNode(value=ProbabilityValue([0.0, 0.0, 0.0, 0.0, 1.0],n=17.0)), value=ProbabilityValue([0.0, 0.0, 0.045454545454545456, 0.0, 0.9545454545454546],n=22.0)), neg_child=LeafNode(value=ProbabilityValue([0.2, 0.0, 0.4, 0.2, 0.2],n=5.0)), value=ProbabilityValue([0.037037037037037035, 0.0, 0.1111111111111111, 0.037037037037037035, 0.8148148148148148],n=27.0)), neg_child=NonLeafNode(condition=(Bacteroides >= 0.0034175491891801357; miss=True), pos_child=LeafNode(value=ProbabilityVa

In [51]:
# number_of_use[F] will be the number of node using feature F in its condition.
number_of_use = collections.defaultdict(lambda: 0)

# Iterate over all the nodes in a Depth First Pre-order traversals.
for node_iter in inspector.iterate_on_nodes():

  if not isinstance(node_iter.node, tfdf.py_tree.node.NonLeafNode):
    # Skip the leaf nodes
    continue

  # Iterate over all the features used in the condition.
  # By default, models are "oblique" i.e. each node tests a single feature.
  for feature in node_iter.node.condition.features():
    number_of_use[feature] += 1

print("Number of condition nodes per features:")
for feature, count in number_of_use.items():
  print("\t", feature.name, ":", count)

Number of condition nodes per features:
	 uncultured/unidentified-total : 579
	 Prevotella-Total : 339
	 Coprococcus-Total : 374
	 Blautia : 378
	 Dorea : 424
	 Lactobacillus : 408
	 Faecalibacterium : 340
	 Ruminococcus-Total : 282
	 Collinsella : 385
	 Ruminococcaceae-Total : 378
	 Dialister : 361
	 Bifidobacterium : 399
	 Other-Total : 337
	 Alloprevotella : 406
	 Bacteroides : 378
	 Lachnospiraceae-Total : 399
	 Streptococcus-total : 358
	 Roseburia : 582
	 Escherichia-Shigella : 498
